import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const grafmassaItalic = localFont({
  src: "./fonts/Grafmassa-Italic.woff",
  variable: "--font-grafmassa-italic", // Unique variable for Grafmassa Italic
  weight: "100 900",
});
const grafmassaRegular = localFont({
  src: "./fonts/Grafmassa-Regular.woff",
  variable: "--font-grafmassa-regular", // Unique variable for Grafmassa Regular
  weight: "100 900",
});
const hooskai = localFont({
  src: "./fonts/HooskaiChamferedSquare.woff",
  variable: "--font-hooskai", // Unique variable for Hooskai
  weight: "100 900",
});
const quantum = localFont({
  src: "./fonts/quantum.woff",
  variable: "--font-quantum", // Unique variable for Quantum
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Tony Stark",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hooskai.variable} ${quantum.variable} ${grafmassaItalic.variable} ${grafmassaRegular.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
